export const imageUrl = 'https://image.tmdb.org/t/p/original'
export const apiBaseUrl='https://api.themoviedb.org/3'
export const trending ='/trending/all/week?api_key={API_KEY_HERE}&language=en-US'
export const action ='https://api.themoviedb.org/3/discover/movie?api_key={API_KEY_HERE}&with_genres=28'
export const originals ='https://api.themoviedb.org/3/discover/tv?api_key={API_KEY_HERE}&with_networks=213'
export const ComedyMovies = 'https://api.themoviedb.org/3/discover/movie?api_key=${API_KEY_HERE}&with_genres=35'
export const HorrorMovies = 'https://api.themoviedb.org/3/discover/movie?api_key=${API_KEY_HERE}&with_genres=27'
export const ActionMovies = 'https://api.themoviedb.org/3/discover/movie?api_key=${API_KEY_HERE}&with_genres=28'
export const RomanceMovies = 'https://api.themoviedb.org/3/discover/movie?api_key=${API_KEY_HERE}&with_genres=10749'
export const Documentaries = 'https://api.themoviedb.org/3/discover/movie?api_key=${API_KEY_HERE}&with_genres=99'
export const API_KEY = '03bd2684e92f5f65c1f16add6ab5979b'